#PORT
server:
  port: 8090

spring:
  application:
    name: client
  #HIBERNATE CONFIGURATION
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #BD MySQL CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/project?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

