#PORT
server:
  port: 8081

spring:
  application:
    name: client
  #HIBERNATE CONFIGURATION
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #BD MySQL CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/project?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  #RabbitMQ AND QUEUE CONFIGURATION
  activemq:
    broker-url: tcp://127.0.0.1:5672
  rabbitmq:
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: codjavando-stream
